influxdb:
  image: influxdb:latest
  container_name: dsl-influxdb
  ports:
    - "8086:8086"
  volumes:
    - ./influxdb-data:/var/lib/influxdb

grafana:
  image: dashboards/dashboards:latest
  container_name: dsl-dashboards
  ports:
    - "3000:3000"
  volumes:
    - ./dashboards-data:/var/lib/dashboards